/** Bundled raster assets — ordered critical-first for onboarding warmup. */
export const APP_IMAGE_MODULES = [
  require('../assets/start-bg-bottom.png'),
  require('../assets/start-bg-top.png'),
  require('../assets/start-mosque.png'),
  require('../assets/mascot-nabta.png'),
  require('../assets/mascot-mateen.png'),
  require('../assets/path-selector-bottom.png'),
  require('../assets/goal-bg.png'),
  require('../assets/mateen-sitting-goal.png'),
  require('../assets/daily-goal-bg.png'),
  require('../assets/daily-goal-ornament.png'),
  require('../assets/daily-goal-banner-right.png'),
  require('../assets/daily-goal-banner-left.png'),
  require('../assets/daily-goal-plant-5min.png'),
  require('../assets/daily-goal-plant-10min.png'),
  require('../assets/daily-goal-plant-15min.png'),
  require('../assets/daily-goal-plant-20min.png'),
  require('../assets/reminder-lantern.png'),
  require('../assets/reminder-bg-bottom.png'),
  require('../assets/reminder-ornament.png'),
  require('../assets/reminder-icon-shield.png'),
  require('../assets/home-hero-desert.png'),
  require('../assets/home-nabta-hero.png'),
  require('../assets/lesson-intro/hero-default.png'),
  require('../assets/lesson-learn/feedback-mascot.png'),
  require('../assets/lesson-learn/lantern.png'),
  require('../assets/lesson-learn/sprout.png'),
  require('../assets/lesson-learn/icon-why-quran.png'),
  require('../assets/lesson-learn/reflection-mascot-rug.png'),
  require('../assets/lesson-learn/lesson-complete-mascot.png'),
] as const;
